# Generated by Django 2.2 on 2022-12-11 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='price',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
