# Generated by Django 2.2 on 2022-12-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='type',
            field=models.TextField(null=True),
        ),
    ]
