# Generated by Django 2.2 on 2022-12-14 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_cards_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=30)),
                ('contacts', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254, verbose_name='')),
            ],
        ),
    ]
