# Generated by Django 2.2 on 2022-12-12 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20221211_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabriolets',
            name='year',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='jeep',
            name='year',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='limousine',
            name='year',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='premium',
            name='year',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='retro',
            name='year',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='year',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
