# Generated by Django 2.2 on 2022-12-12 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20221212_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabriolets',
            name='color',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='cabriolets',
            name='seats',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='jeep',
            name='color',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='jeep',
            name='seats',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='limousine',
            name='color',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='limousine',
            name='seats',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='premium',
            name='color',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='premium',
            name='seats',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='retro',
            name='color',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='retro',
            name='seats',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='color',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='seats',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
