# Generated by Django 2.2 on 2022-12-14 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('fullname', models.CharField(max_length=255)),
                ('number', models.IntegerField()),
                ('typeofcar', models.TextField()),
                ('nameofcar', models.TextField()),
                ('data', models.DateTimeField()),
            ],
        ),
    ]
