# Generated by Django 2.2 on 2022-12-12 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model_notes_of_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_note', models.CharField(max_length=200)),
                ('text_note', models.TextField()),
                ('date_note', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
